async function loadVirtualEnv(): Promise<Record<string, unknown> | undefined> {
	try {
		// @ts-ignore - virtual module, generated by the Astro integration
		const { env } = (await import("virtual:emdash/env")) as {
			env?: Record<string, unknown>;
		};
		if (typeof env === "object" && env !== null) return env;
		return undefined;
	} catch {
		return undefined;
	}
}

async function loadWorkersEnv(): Promise<Record<string, unknown> | undefined> {
	try {
		const { env } = await import("cloudflare:workers");
		if (typeof env === "object" && env !== null) {
			return Object.fromEntries(Object.entries(env));
		}

		return undefined;
	} catch {
		return undefined;
	}
}

export async function resolveOAuthEnv(
	locals: unknown,
	fallbackEnv: Record<string, unknown>,
	loadEnv: () => Promise<Record<string, unknown> | undefined> = loadWorkersEnv,
): Promise<Record<string, unknown>> {
	void locals;

	const virtualEnv = await loadVirtualEnv();
	if (virtualEnv) return virtualEnv;

	try {
		const workersEnv = await loadEnv();
		return workersEnv ?? fallbackEnv;
	} catch {
		return fallbackEnv;
	}
}
