function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null;
}

async function loadVirtualEnv(): Promise<Record<string, unknown> | undefined> {
	try {
		// @ts-ignore - virtual module, generated by the Astro integration
		const { env } = (await import("virtual:emdash/env")) as {
			env?: Record<string, unknown>;
		};
		if (isRecord(env)) return env;
		return undefined;
	} catch {
		return undefined;
	}
}

function readRuntimeEnv(locals: unknown): Record<string, unknown> | undefined {
	try {
		if (typeof locals !== "object" || locals === null) return undefined;

		const runtime = Reflect.get(locals, "runtime");
		if (!isRecord(runtime)) return undefined;

		const env = Reflect.get(runtime, "env");
		return isRecord(env) ? env : undefined;
	} catch {
		return undefined;
	}
}

async function loadWorkersEnv(): Promise<Record<string, unknown> | undefined> {
	try {
		const { env } = await import("cloudflare:workers");
		if (typeof env === "object" && env !== null) {
			return Object.fromEntries(Object.entries(env));
		}

		return undefined;
	} catch {
		return undefined;
	}
}

export async function resolveOAuthEnv(
	locals: unknown,
	fallbackEnv: Record<string, unknown>,
	loadEnv: () => Promise<Record<string, unknown> | undefined> = loadWorkersEnv,
): Promise<Record<string, unknown>> {
	const runtimeEnv = readRuntimeEnv(locals);
	if (runtimeEnv) return runtimeEnv;

	const virtualEnv = await loadVirtualEnv();
	if (virtualEnv) return virtualEnv;

	try {
		const workersEnv = await loadEnv();
		return workersEnv ?? fallbackEnv;
	} catch {
		return fallbackEnv;
	}
}
